import type { IconType } from "react-icons";
import { BsBing } from "react-icons/bs";
import { FaLinkedin, FaSlack } from "react-icons/fa";
import { FiCpu, FiGlobe, FiPlus, FiType } from "react-icons/fi";
import {
  SiApple,
  SiBrave,
  SiClaude,
  SiCloudflare,
  SiDiscord,
  SiDropbox,
  SiDuckduckgo,
  SiFigma,
  SiGithub,
  SiGmail,
  SiGoogle,
  SiGooglecalendar,
  SiGoogledrive,
  SiGooglegemini,
  SiInstagram,
  SiLinear,
  SiMedium,
  SiNetflix,
  SiNotion,
  SiOpenaigym,
  SiPerplexity,
  SiPinterest,
  SiReddit,
  SiSpotify,
  SiStripe,
  SiSubstack,
  SiTelegram,
  SiThreads,
  SiTiktok,
  SiTwitch,
  SiVercel,
  SiWhatsapp,
  SiX,
  SiYoutube,
} from "react-icons/si";

export const LETTER_ICON = "letter";

export const iconChoices = [
  LETTER_ICON,
  "globe",
  "openai",
  "claude",
  "gemini",
  "github",
  "notion",
  "youtube",
  "gmail",
  "drive",
  "calendar",
  "reddit",
  "x",
  "threads",
  "linkedin",
  "instagram",
  "tiktok",
  "pinterest",
  "spotify",
  "figma",
  "linear",
  "vercel",
  "discord",
  "slack",
  "telegram",
  "whatsapp",
  "twitch",
  "stripe",
  "netflix",
  "apple",
  "dropbox",
  "cloudflare",
  "medium",
  "substack",
] as const;

const iconMap: Record<string, { icon: IconType; color: string; label: string }> = {
  openai: { icon: SiOpenaigym, color: "#119b75", label: "OpenAI" },
  github: { icon: SiGithub, color: "#181717", label: "GitHub" },
  notion: { icon: SiNotion, color: "#111111", label: "Notion" },
  youtube: { icon: SiYoutube, color: "#ff0033", label: "YouTube" },
  play: { icon: SiYoutube, color: "#ff0033", label: "YouTube" },
  gmail: { icon: SiGmail, color: "#ea4335", label: "Gmail" },
  drive: { icon: SiGoogledrive, color: "#34a853", label: "Google Drive" },
  calendar: { icon: SiGooglecalendar, color: "#4285f4", label: "Google Calendar" },
  reddit: { icon: SiReddit, color: "#ff4500", label: "Reddit" },
  x: { icon: SiX, color: "#111111", label: "X" },
  linkedin: { icon: FaLinkedin, color: "#0a66c2", label: "LinkedIn" },
  spotify: { icon: SiSpotify, color: "#1db954", label: "Spotify" },
  figma: { icon: SiFigma, color: "#a259ff", label: "Figma" },
  linear: { icon: SiLinear, color: "#5e6ad2", label: "Linear" },
  vercel: { icon: SiVercel, color: "#111111", label: "Vercel" },
  google: { icon: SiGoogle, color: "#4285f4", label: "Google" },
  bing: { icon: BsBing, color: "#008373", label: "Bing" },
  duckduckgo: { icon: SiDuckduckgo, color: "#de5833", label: "DuckDuckGo" },
  brave: { icon: SiBrave, color: "#fb542b", label: "Brave" },
  perplexity: { icon: SiPerplexity, color: "#1f8a89", label: "Perplexity" },
  chatgpt: { icon: SiOpenaigym, color: "#119b75", label: "ChatGPT" },
  claude: { icon: SiClaude, color: "#cc785c", label: "Claude" },
  gemini: { icon: SiGooglegemini, color: "#6e7cf6", label: "Gemini" },
  copilot: { icon: BsBing, color: "#0078d4", label: "Copilot" },
  you: { icon: FiCpu, color: "#6f4dff", label: "You.com" },
  phind: { icon: FiCpu, color: "#5f6f8a", label: "Phind" },
  globe: { icon: FiGlobe, color: "#2f8f83", label: "Website" },
  add: { icon: FiPlus, color: "#66736c", label: "Add" },
  letter: { icon: FiType, color: "#66736c", label: "Letter" },
  discord: { icon: SiDiscord, color: "#5865f2", label: "Discord" },
  slack: { icon: FaSlack, color: "#611f69", label: "Slack" },
  telegram: { icon: SiTelegram, color: "#229ed9", label: "Telegram" },
  whatsapp: { icon: SiWhatsapp, color: "#25d366", label: "WhatsApp" },
  twitch: { icon: SiTwitch, color: "#9146ff", label: "Twitch" },
  stripe: { icon: SiStripe, color: "#635bff", label: "Stripe" },
  netflix: { icon: SiNetflix, color: "#e50914", label: "Netflix" },
  apple: { icon: SiApple, color: "#111111", label: "Apple" },
  dropbox: { icon: SiDropbox, color: "#0061ff", label: "Dropbox" },
  cloudflare: { icon: SiCloudflare, color: "#f38020", label: "Cloudflare" },
  medium: { icon: SiMedium, color: "#111111", label: "Medium" },
  substack: { icon: SiSubstack, color: "#ff6719", label: "Substack" },
  threads: { icon: SiThreads, color: "#111111", label: "Threads" },
  instagram: { icon: SiInstagram, color: "#e1306c", label: "Instagram" },
  tiktok: { icon: SiTiktok, color: "#111111", label: "TikTok" },
  pinterest: { icon: SiPinterest, color: "#e60023", label: "Pinterest" },
};

export function getBrandIcon(name: string) {
  return iconMap[name] ?? iconMap.globe;
}
